[pytest]
testpaths = motor_test/test_cases
norecursedirs = .git .cache .pytest_cache build
cache_dir = .pytest_cache
filterwarnings =
    ignore:pkg_resources is deprecated as an API\..*:DeprecationWarning:can\.io\.logger
    ignore:Deprecated call to `pkg_resources\.declare_namespace\('google'\)`\..*:DeprecationWarning:pkg_resources
    ignore:Deprecated call to `pkg_resources\.declare_namespace\('mpl_toolkits'\)`\..*:DeprecationWarning:pkg_resources
