/*
 * Copyright 2020-2025 Yuntu Microelectronics Co., Ltd.
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * @file can_config.h
 * @brief CAN FD configuration and motor telemetry/command protocol.
 *
 * DBC file: docs/motor_control.dbc (generated by .scripts/generate_dbc.py)
 * Bus:      CAN FD 500K/2M, PE Clock 120 MHz
 */

#ifndef __CAN_CONFIG_H__
#define __CAN_CONFIG_H__

#include <stdbool.h>
#include <stdint.h>

#include "flexcan_driver.h"

/* ═══════════════════════════════════════════════════════════════════════════════
 * CAN Instance & Pin Configuration
 * ═══════════════════════════════════════════════════════════════════════════════
 */

/** @brief FlexCAN peripheral instance index (CAN0). */
#define CAN_CFG_INSTANCE (0U)

/** @brief CAN transceiver standby pin (PTE10, active low). */
#define CAN_CFG_STB_PORT GPIOE
#define CAN_CFG_STB_PIN (10U)

/* ═══════════════════════════════════════════════════════════════════════════════
 * CAN FD Bitrate (PE Clock = 120 MHz)
 * ═══════════════════════════════════════════════════════════════════════════════
 */

/**
 * Arbitration phase: 500 kbit/s
 *   Tq = (preDivider + 1) / 120 MHz = 15/120M = 125 ns
 *   NBT = 1 + propSeg + phaseSeg1 + phaseSeg2 + 1 = 1+5+5+4+1 = 16 Tq
 *   Bitrate = 1 / (16 × 125 ns) = 500 kbit/s
 *   Sample point = (1+5+5)/(16) = 68.75%
 */
#define CAN_CFG_ARB_PREDIV (11U)
#define CAN_CFG_ARB_PROPSEG (7U)
#define CAN_CFG_ARB_PSEG1 (5U)
#define CAN_CFG_ARB_PSEG2 (4U)
#define CAN_CFG_ARB_RJUMP (3U)

/**
 * Data phase: 2 Mbit/s
 *   Tq = (preDivider + 1) / 120 MHz = 3/120M = 25 ns
 *   DBT = 1 + propSeg + phaseSeg1 + phaseSeg2 + 1 = 1+6+7+5+1 = 20 Tq
 *   Bitrate = 1 / (20 × 25 ns) = 2 Mbit/s
 *   Sample point = (1+6+7)/(20) = 70%
 */
#define CAN_CFG_DATA_PREDIV (2U)
#define CAN_CFG_DATA_PROPSEG (6U)
#define CAN_CFG_DATA_PSEG1 (6U)
#define CAN_CFG_DATA_PSEG2 (5U)
#define CAN_CFG_DATA_RJUMP (3U)

/**
 * TDC (Transmitter Delay Compensation) offset for data phase.
 *   TDC_offset = propSeg + phaseSeg1 + transceiver_pipeline_Tq
 *              = 6 + 7 + 1 = 14 Tq (@ Tq = 25 ns → 350 ns physical offset)
 * Set >= actual loop delay to ensure receiver samples after the echo.
 */
#define CAN_CFG_TDC_OFFSET (14U)

/* ═══════════════════════════════════════════════════════════════════════════════
 * Message IDs (must match docs/motor_control.dbc)
 * ═══════════════════════════════════════════════════════════════════════════════
 */

#define CAN_MSG_ID_MOTOR_STATUS1 (0x180U)  /**< MCU→PC, 10ms  */
#define CAN_MSG_ID_MOTOR_STATUS2 (0x181U)  /**< MCU→PC, 10ms  */
#define CAN_MSG_ID_CALIB_READBACK (0x182U) /**< MCU→PC, 200ms */
#define CAN_MSG_ID_MOTOR_STATUS3 (0x183U)  /**< MCU→PC, burst */
#define CAN_MSG_ID_MOTOR_COMMAND (0x200U)  /**< PC→MCU, event */
#define CAN_MSG_ID_CALIB_WRITE (0x201U)    /**< PC→MCU, event */
#define CAN_MSG_ID_TEST_COMMAND (0x202U)   /**< PC→MCU, event */

/** @brief CAN FD data payload size in bytes (64). */
#define CAN_MSG_DLC (64U)

/* ═══════════════════════════════════════════════════════════════════════════════
 * TX/RX Message Buffer Assignments
 * ═══════════════════════════════════════════════════════════════════════════════
 */

#define CAN_MB_TX_STATUS1 (0U)
#define CAN_MB_TX_STATUS2 (1U)
#define CAN_MB_TX_CALIB_READBACK (2U)
#define CAN_MB_TX_STATUS3 (3U)
#define CAN_MB_RX_COMMAND (4U)
#define CAN_MB_RX_CALIB_WRITE (5U)
#define CAN_MB_RX_TEST_COMMAND (6U)

/* ═══════════════════════════════════════════════════════════════════════════════
 * TX Cycle Periods (milliseconds)
 * ═══════════════════════════════════════════════════════════════════════════════
 */

#define CAN_TX_PERIOD_STATUS1_MS (10U)
#define CAN_TX_PERIOD_STATUS2_MS (10U)
#define CAN_TX_PERIOD_CALIB_MS (200U)

/* ═══════════════════════════════════════════════════════════════════════════════
 * Calibration Parameter Storage (RAM only)
 * ═══════════════════════════════════════════════════════════════════════════════
 */

/**
 * @brief Online-tunable calibration parameters received via PC_CalibWrite.
 *
 * These are kept in RAM and applied at runtime. They mirror the default
 * compile-time constants in motor_user_config.h but can be overridden
 * by the CAN calibration interface for automated test sweeps.
 */
typedef struct {
  /* Speed PI */
  float speed_kp; /**< Speed loop proportional gain.      */
  float speed_ki; /**< Speed loop integral gain.          */

  /* Current PI (runtime override for FOC current loop) */
  float current_id_kp; /**< D-axis current PI Kp (V/A).       */
  float current_id_ki; /**< D-axis current PI Ki (V/A/s).     */
  float current_iq_kp; /**< Q-axis current PI Kp (V/A).       */
  float current_iq_ki; /**< Q-axis current PI Ki (V/A/s).     */

  /* Observer */
  float observer_gain; /**< Ortega observer correction gain.   */
  float pll_kp;        /**< PLL proportional gain.             */
  float pll_ki;        /**< PLL integral gain.                 */

  /* Limits */
  float max_iq_a;             /**< Maximum Iq clamp (A).              */
  float open_loop_iq_a;       /**< Open-loop Iq target (A).           */
  float align_current_a;      /**< Alignment d-axis current (A).      */
  float fw_voltage_threshold; /**< Field weakening voltage threshold. */
  float speed_ramp_rpm_per_s; /**< Speed ramp rate (rpm/s).           */

  bool pending;   /**< True when new values received.     */
  bool committed; /**< True after CalibApply = 0xFF.      */
} can_calib_params_t;

/* ═══════════════════════════════════════════════════════════════════════════════
 * Waveform Burst Capture (Status3)
 * ═══════════════════════════════════════════════════════════════════════════════
 */

/** @brief Maximum samples per waveform capture burst. */
#define CAN_WAVEFORM_MAX_SAMPLES (256U)

/** @brief Number of float channels per waveform sample. */
#define CAN_WAVEFORM_CHANNELS (7U)

/**
 * @brief Waveform capture trigger source.
 */
typedef enum {
    CAN_WAVEFORM_TRIG_NONE    = 0,  /**< No active capture.           */
    CAN_WAVEFORM_TRIG_MANUAL  = 1,  /**< PC-triggered manual capture. */
    CAN_WAVEFORM_TRIG_STARTUP = 2,  /**< Auto-capture on startup.     */
    CAN_WAVEFORM_TRIG_FAULT   = 3,  /**< Auto-capture on fault.       */
} can_waveform_trigger_t;

/**
 * @brief Waveform capture state.
 */
typedef enum {
    CAN_WAVEFORM_IDLE      = 0,  /**< Not capturing.               */
    CAN_WAVEFORM_CAPTURING = 1,  /**< Currently recording samples. */
    CAN_WAVEFORM_SENDING   = 2,  /**< Uploading via Status3 burst.  */
    CAN_WAVEFORM_DONE      = 3,  /**< Upload complete.              */
} can_waveform_state_t;

/**
 * @brief Per-sample waveform data captured at PWM rate.
 *
 * Channels: Ia, Ib, Ic, Vbus, Id, Iq, ElecAngle
 */
typedef struct {
    float channels[CAN_WAVEFORM_CHANNELS];
} can_waveform_sample_t;

/**
 * @brief Waveform capture control block.
 */
typedef struct {
    can_waveform_trigger_t trigger;  /**< What triggered this capture.    */
    can_waveform_state_t   state;    /**< Current capture state.          */
    uint16_t               n_samples;/**< Requested number of samples.    */
    uint16_t               write_idx;/**< Current write index.            */
    uint16_t               send_idx; /**< Current send index (for burst). */
    uint8_t                decimation;/**< Sample every N fast-loop ticks. */
    uint8_t                tick_count;/**< Internal tick counter.          */
    can_waveform_sample_t  samples[CAN_WAVEFORM_MAX_SAMPLES];
} can_waveform_capture_t;

/**
 * @brief Temperature readings structure.
 */
typedef struct {
  float pcb_temperature_degc;  /**< PCB board temperature (°C).        */
  float chip_temperature_degc; /**< MCU die temperature (°C).          */
} can_temperature_t;

/* ═══════════════════════════════════════════════════════════════════════════════
 * Public API
 * ═══════════════════════════════════════════════════════════════════════════════
 */

/**
 * @brief Initialize FlexCAN FD peripheral and configure TX/RX message buffers.
 *
 * Must be called after Board_Init() and before MotorControl_Init().
 * Enables CAN0 in CAN FD mode (500K/2M) with 64-byte payloads.
 */
void CanConfig_Init(void);

/**
 * @brief Periodic CAN task — call from main loop at >= 1 kHz rate.
 *
 * Manages TX scheduling (Status1 @ 10ms, Status2 @ 50ms, CalibReadback @ 200ms)
 * and processes any received RX commands.
 *
 * @param tickMs Current system tick in milliseconds.
 */
void CanConfig_Task(uint32_t tickMs);

/**
 * @brief Update temperature readings for CAN telemetry.
 *
 * @param pcbTemp  PCB board temperature in °C.
 * @param chipTemp MCU die temperature in °C.
 */
void CanConfig_SetTemperatures(float pcbTemp, float chipTemp);

/**
 * @brief Get pointer to active calibration parameters.
 * @return Pointer to the calibration parameter struct (read-only).
 */
const can_calib_params_t *CanConfig_GetCalibParams(void);

/**
 * @brief Check if new calibration parameters have been committed.
 *
 * After this returns true, the caller should apply the new parameters
 * to the motor control and then call CanConfig_AckCalibApplied().
 *
 * @return True if parameters were committed via CAN.
 */
bool CanConfig_IsCalibCommitted(void);

/**
 * @brief Acknowledge that calibration parameters have been applied.
 *
 * Clears the committed flag after the application layer has consumed
 * the new parameter values.
 */
void CanConfig_AckCalibApplied(void);

/**
 * @brief Call from the fast-loop ISR to record one waveform sample.
 *
 * If a waveform capture is active, stores the provided channel data
 * into the ring buffer. Must be called at PWM rate.
 *
 * @param ia   Phase A current (A).
 * @param ib   Phase B current (A).
 * @param ic   Phase C current (A).
 * @param vbus Bus voltage (V).
 * @param id   D-axis current (A).
 * @param iq   Q-axis current (A).
 * @param angle Electrical angle (rad).
 */
void CanConfig_WaveformSample(float ia, float ib, float ic, float vbus,
                              float id, float iq, float angle);

/**
 * @brief Get the current waveform capture state.
 * @return Current waveform state enum value.
 */
can_waveform_state_t CanConfig_GetWaveformState(void);

#endif /* __CAN_CONFIG_H__ */
