/*
 * Copyright 2020-2025 Yuntu Microelectronics Co., Ltd.
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * @file pin_mux.c
 * @brief
 *
 */

#include "pin_mux.h"

/*! @brief User configuration cfg InitConfigArr0 array */
const pin_settings_config_t g_pin_mux_InitConfigArr0[NUM_OF_CONFIGURED_PINS0] =
    {
        /* PTE_11-3-GPIO-START_STOP */
        {
            .base = PCTRLE,
            .pinPortIdx = 11U,
            .pullConfig = PCTRL_INTERNAL_PULL_UP_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_AS_GPIO,
            .intConfig = PCTRL_INT_FALLING_EDGE,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOE,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTE_10-4-GPIO-CAN0_STB */
        {
            .base = PCTRLE,
            .pinPortIdx = 10U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_AS_GPIO,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOE,
            .direction = GPIO_OUTPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTE_5-5-CAN0_TX-CAN0_TX */
        {
            .base = PCTRLE,
            .pinPortIdx = 5U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT5,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOE,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTE_4-6-CAN0_RX-CAN0_RX */
        {
            .base = PCTRLE,
            .pinPortIdx = 4U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT5,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOE,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTE_3-13-GPIO-MOTOR_DIR */
        {
            .base = PCTRLE,
            .pinPortIdx = 3U,
            .pullConfig = PCTRL_INTERNAL_PULL_UP_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_AS_GPIO,
            .intConfig = PCTRL_INT_FALLING_EDGE,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOE,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTE_9-16-eTMR0_CH7-PWM5 */
        {
            .base = PCTRLE,
            .pinPortIdx = 9U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT2,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOE,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTE_8-17-eTMR0_CH6-PWM4 */
        {
            .base = PCTRLE,
            .pinPortIdx = 8U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT2,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOE,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTB_5-18-eTMR0_CH5-PWM3 */
        {
            .base = PCTRLB,
            .pinPortIdx = 5U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT2,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOB,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTB_4-19-eTMR0_CH4-PWM2 */
        {
            .base = PCTRLB,
            .pinPortIdx = 4U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT2,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOB,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTC_3-20-ADC0_SE11 ACMP0_IN4-BEMF_V */
        {
            .base = PCTRLC,
            .pinPortIdx = 3U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_PIN_DISABLED,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOC,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTC_2-21-ADC0_SE10 ACMP0_IN5-BEMF_W */
        {
            .base = PCTRLC,
            .pinPortIdx = 2U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_PIN_DISABLED,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOC,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTC_1-25-eTMR0_CH1-PWM1 */
        {
            .base = PCTRLC,
            .pinPortIdx = 1U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT2,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOC,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTC_0-26-eTMR0_CH0-PWM0 */
        {
            .base = PCTRLC,
            .pinPortIdx = 0U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT2,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOC,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTC_17-27-GPIO-HALL1 */
        {
            .base = PCTRLC,
            .pinPortIdx = 17U,
            .pullConfig = PCTRL_INTERNAL_PULL_DOWN_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_AS_GPIO,
            .intConfig = PCTRL_INT_EITHER_EDGE,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOC,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTC_16-28-GPIO-HALL2 */
        {
            .base = PCTRLC,
            .pinPortIdx = 16U,
            .pullConfig = PCTRL_INTERNAL_PULL_DOWN_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_AS_GPIO,
            .intConfig = PCTRL_INT_EITHER_EDGE,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOC,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTB_3-31-GPIO-HALL3 */
        {
            .base = PCTRLB,
            .pinPortIdx = 3U,
            .pullConfig = PCTRL_INTERNAL_PULL_DOWN_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_AS_GPIO,
            .intConfig = PCTRL_INT_EITHER_EDGE,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOB,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTB_2-32-ADC0_SE6-TempSensor */
        {
            .base = PCTRLB,
            .pinPortIdx = 2U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_PIN_DISABLED,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOB,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTB_1-33-ADC0_SE5-VdcBusSense */
        {
            .base = PCTRLB,
            .pinPortIdx = 1U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_PIN_DISABLED,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOB,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTB_0-34-ADC0_SE4-CurrentC */
        {
            .base = PCTRLB,
            .pinPortIdx = 0U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_PIN_DISABLED,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOB,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTC_9-35-LINFlexD1_TX-UART1_TXD */
        {
            .base = PCTRLC,
            .pinPortIdx = 9U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT2,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOC,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTC_8-36-LINFlexD1_RX-UART1_RXD */
        {
            .base = PCTRLC,
            .pinPortIdx = 8U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT2,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOC,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTA_7-37-ADC0_SE3-CurrentB */
        {
            .base = PCTRLA,
            .pinPortIdx = 7U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_PIN_DISABLED,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOA,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTA_6-38-ADC0_SE2-CurrentA */
        {
            .base = PCTRLA,
            .pinPortIdx = 6U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_PIN_DISABLED,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOA,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTD_3-45-GPIO-LED1 */
        {
            .base = PCTRLD,
            .pinPortIdx = 3U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_AS_GPIO,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOD,
            .direction = GPIO_OUTPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTD_2-46-GPIO-LED2 */
        {
            .base = PCTRLD,
            .pinPortIdx = 2U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_AS_GPIO,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOD,
            .direction = GPIO_OUTPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTA_1-49-ADC0_SE1 ACMP0_IN1-BEMF_U */
        {
            .base = PCTRLA,
            .pinPortIdx = 1U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_PIN_DISABLED,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOA,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTA_0-50-ADC0_SE0 ACMP0_IN0-BEMF_COM */
        {
            .base = PCTRLA,
            .pinPortIdx = 0U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_PIN_DISABLED,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOA,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTC_7-51-eTMR1_QD_PHA-QDA */
        {
            .base = PCTRLC,
            .pinPortIdx = 7U,
            .pullConfig = PCTRL_INTERNAL_PULL_UP_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT6,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOC,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTC_6-52-eTMR1_QD_PHB-QDB */
        {
            .base = PCTRLC,
            .pinPortIdx = 6U,
            .pullConfig = PCTRL_INTERNAL_PULL_UP_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT6,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOC,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTA_12-56-eTMR1_CH6-PWM_IN */
        {
            .base = PCTRLA,
            .pinPortIdx = 12U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT2,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOA,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
        /* PTA_11-57-eTMR1_CH5-PWM_OUT */
        {
            .base = PCTRLA,
            .pinPortIdx = 11U,
            .pullConfig = PCTRL_INTERNAL_PULL_NOT_ENABLED,
            .rateSelect = PCTRL_FAST_SLEW_RATE,
            .passiveFilter = false,
            .driveSelect = PCTRL_LOW_DRIVE_STRENGTH,
            .mux = PCTRL_MUX_ALT2,
            .intConfig = PCTRL_DMA_INT_DISABLED,
            .clearIntFlag = false,
            .digitalFilter = false,
            .gpioBase = GPIOA,
            .direction = GPIO_INPUT_DIRECTION,
            .initValue = 0,
        },
};

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
